services:
  db:
    image: postgres:16
    container_name: second_brain_db_v2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata_v2:/var/lib/postgresql/data

volumes:
  pgdata_v2: