[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.12"
description = ""
authors = []
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.135.0",
    "psycopg[binary]>=3.3.3",
    "pydantic-settings>=2.13.1",
    "sqlalchemy>=2.0.48",
]

[tool.ruff]
line-length = 100

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    "F",    # pyflakes
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "I",    # isort
]
ignore = [
    "E203"  # not PEP8 compliant
]

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.4",
]
